use SHA-384 for nisp384 curve
simo5/ietf pull request #10
Opened 2017-04-19 12:58 UTC by tomato42

since RFC5656 uses sha-384 with the nisp384 curve, be consistent
and use it here too

Posted here for completeness, I'm not entirely convinced that this is necessary or welcome (in that it will make implementation easier)

2017-04-21 19:31 UTC, simo5 requested changes
Maybe fixup curve names here as well while changing the hash type ?

2017-04-21 19:31 UTC, simo5 commented on draft-ssorce-gss-keyex-sha2.xml
> +          <c>gss-secp384r1-sha384-*</c><c>MAY/OPTIONAL</c>
shouldn;t these names be changed to nistp384 etc ..?

2017-04-21 19:56 UTC, tomato42 commented on draft-ssorce-gss-keyex-sha2.xml
> +          <c>gss-secp384r1-sha384-*</c><c>MAY/OPTIONAL</c>
yes, I need to rebase it

2017-04-26 18:12 UTC, simo5 commented
I included a rebased version in #13

2017-04-26 18:12 UTC, closed without merging