Define method names via family name table
simo5/ietf pull request #23
Opened 2018-04-19 18:23 UTC by simo5

avoid repeting the same text over and instead use tables to reference groups and curves in new method families.

2018-04-19 18:24 UTC, simo5 commented
@tomato42 PTAL

2018-04-20 11:23 UTC, tomato42 requested changes

2018-04-20 11:23 UTC, tomato42 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +          <c>gss-group14-sha256</c><c>SHA-256</c><c>2048-bit MODP</c>
isn't the `-` at the end of the name quite crucial?

2018-04-20 11:23 UTC, tomato42 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +          <c>gss-nistp256-sha256</c><c>SHA-256</c><c>secp256r1</c>
same here, missing `-` at the end of prefix

2018-04-20 11:31 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +          <c>gss-group14-sha256</c><c>SHA-256</c><c>2048-bit MODP</c>
Uhmmm I guess I can see how it could be amiguous without, thanks

2018-04-20 11:33 UTC, simo5 commented
@tomato42 fixed prefix names PTAL

2018-04-20 13:09 UTC, tomato42 approved these changes

2018-04-20 13:34 UTC, merged