Use existing standards to define kex calculations
simo5/ietf pull request #24
Opened 2018-04-25 18:47 UTC by tomato42

Use existing standards to describe key exchange

plus a small fix for address

2018-04-25 18:54 UTC, simo5 requested changes
Mostly minor nitpicks

2018-04-25 18:54 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +                <t>Following algorithm in Section 3.2.1 of
the algorithm

2018-04-25 18:54 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +                <t>Coverting the resulting point q_C to the Q_C octet string
Converting

2018-04-25 18:54 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +                using algorithm in Section 2.3.4 of <xref target="SEC1v2"/>.
the algorithm

2018-04-25 18:54 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +            <t>For NIST curves, the server performs a partial public key
the partial

2018-04-25 18:54 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +              <t>For NIST curves, the peers calculate shared secret field
the shared secret

2018-04-25 18:54 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +                  element using d_U and q_V using algorithms in Section 3.3.1
the algorithm

2018-04-25 18:54 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +                  of <xref target="SEC1v2"/>. If the output of that algorithm
If the result is "invalid" ...

2018-04-25 18:54 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +                  representation of the field element using algorithm described
the algorithm

2018-04-25 18:54 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> +                  in Section 2.3.5 in <xref target="SEC1v2"/>.</t>
2.3.5 of

2018-04-25 18:54 UTC, simo5 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> -              <title>Public Key Cryptography for the Financial Services
Why change this ?

2018-04-25 18:58 UTC, tomato42 commented on draft-ietf-curdle-gss-keyex-sha2.xml
> -              <title>Public Key Cryptography for the Financial Services
Because I don't have it on hand

2018-04-26 10:50 UTC, tomato42 commented
@simo5 updated

2018-05-01 19:09 UTC, simo5 approved these changes
LGTM

2018-05-30 14:18 UTC, merged